# Generated by Django 4.1 on 2022-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_year', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=100)),
                ('descritpion', models.CharField(max_length=600)),
                ('free', models.BooleanField()),
            ],
        ),
    ]
