# Generated by Django 4.1 on 2022-08-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_returns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returns',
            options={'ordering': ['-date']},
        ),
    ]
