# Generated by Django 4.1 on 2022-08-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_book_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field=300, upload_to='cover', width_field=200),
        ),
    ]
