# Generated by Django 4.1 on 2022-08-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_raiting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raiting',
        ),
    ]
