# Generated by Django 4.1 on 2022-08-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_raiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rents',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returns',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='rents',
        ),
        migrations.DeleteModel(
            name='Returns',
        ),
    ]
